StoreApp/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Entities.Models;
using Microsoft.AspNetCore.Mvc;
using Repositories.Contracts;
using Services.Contracts;

namespace StoreApp.Controllers
{
    public class CategoryController : Controller
    {
        private readonly IServiceManager _manager;

        public CategoryController(IServiceManager manager)
        {
            _manager = manager;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var category =  _manager.CategoryService.GetAllCategories(false);
            return View(category);
        }
    }
}

StoreApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace StoreApp.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index(){
            return View();
        }
    }
}

StoreApp/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Entities.Models;
using Repositories.EFCore;
using Repositories.Contracts;
using Services.Contracts;

namespace StoreApp.Controllers
{
    public class ProductController : Controller
    {
        private readonly IServiceManager _manager;

        public ProductController(IServiceManager manager)
        {
            _manager = manager;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var model = _manager.ProductService.GetAllProducts(false);
            return View(model);
        }

        [HttpGet]
        public IActionResult Get([FromRoute(Name = "productId")] int productId)
        {
            var product = _manager.ProductService.GetProductById(productId, false);
            return View(product);
        }
    }
}

StoreApp/Views/Category/Index.cshtml
@model IEnumerable<Category>

<div class="text-center">
    <h6 class="display-6">Categories</h6>
</div>

<ul class="list-group my-3">
    @foreach (Category category in Model)
    {
        <li class="list-group-item">@category.CategoryName</li>
    }
</ul>

StoreApp/Views/Home/Index.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
</head>
<body>
    <h1>Home Page</h1>
</body>
</html> 

StoreApp/Views/Product/Get.cshtml
@{
    Layout = "_Layout";
}
@model Product

<h3>@Model.ProductName</h3>
<p>@Model.Price</p>
<div class="btn-group">
    <a class="btn btn-dark" asp-controller="Product" asp-action="Index">
        <i class="fa-solid fa-bars-staggered"></i>
        Products
    </a>
    <a class="btn btn-outline-dark" asp-controller="Home" asp-action="Index">
        <i class="fa-solid fa-house"></i>
        Home
    </a>
</div>

StoreApp/Views/Product/Index.cshtml
@{
    Layout = "_Layout";
}
@model IQueryable<Product>

@section Footer{
    <div>
        Only for index footer
    </div>
}

@* Ekranda satır flowu oluşturur *@
<div class="row my-3">
    @foreach(Product product in Model)
    {

            @* _ProductCard.cshtml çağırdık *@
            <partial name="_ProductCard" model="@product" />


    }
</div>

StoreApp/Views/Product/_ProductCard.cshtml
@model Product

@* Ekranı(12 sütun) 4 sütuna denk gelecek orta boyutta böler. Yan yana 3 iteme izin verir *@
<div class="col-sm-12 col-md-4 col-xxl-3 my-3">
    <div class="card" style="width: 18rem;">
        <img src="~/images/default.jpg" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">@Model.ProductName</h5>
            <p class="card-text">
                <i class="fa-solid fa-money-bills"></i>
                @Model.Price
            </p>
            <p class="card-text">Product Description...</p>
            <a class="btn btn-dark" asp-controller="Product" asp-action="Get" asp-route-productId="@Model.ProductId">
                <i class="fa-solid fa-circle-info"></i>
                Details
            </a>
        </div>
    </div>
</div>

StoreApp/Views/Shared/_Layout.cshtml
@* Ortak sayfa tanımı yaparak her sayfada bulunması gereken yapı tek dosyadan yönetilir *@
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    @* Bootstrap'i libman ile yükledikten sonra projeye dahil ettik *@
    <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.min.css" />
    @* Kendi css dosyamızı dahil ettik *@
    <link rel="stylesheet" href="~/lib/css/site.css" />
    @* Fontawesome'u libman ile yükledikten sonra projeye dahil ettik *@
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.css" />
</head>
<body>

    <header>
        @* _Navbar.cshtml'i çağırdık *@
        <partial name="_Navbar"/>
        @RenderSection("Header", required: false)
    </header>

    @* Container görüntüyü ortaladı *@
    <div class="container">
        @* p-3 tüm eksenlerden padding verdi *@
        <main role="main" class="p-3">
            @RenderBody()
        </main>
    </div>

    <footer>
        Footer
        @RenderSection("Footer", required: false)
    </footer>

    @* JQuery'i libman ile yükledikten sonra projeye dahil ettik *@
    <script src="~/lib/jquery/jquery.min.js"></script>
    @* Bootstrap dahil edildi *@
    <script src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
    @* Kendi js dosyamızı dahil ettik *@
    <script src="~/js/site.js"></script>
    @* Fontawesome dahil edildi *@
    <script src="~/lib/font-awesome/js/all.min.js"></script>


    @* Tüm scriptler yüklendikten sonra çalıştırır *@
    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>

StoreApp/Views/Shared/_Navbar.cshtml
<nav class="navbar navbar-expand-lg bg-body-tertiary border-bottom" data-bs-theme="dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Store App</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-link active" aria-current="page" asp-controller="Home" asp-action="Index">Home</a>
        <a class="nav-link active" aria-current="page" asp-controller="Product" asp-action="Index">Products</a>
        <a class="nav-link active" aria-current="page" asp-controller="Category" asp-action="Index">Categories</a>
      </div>
    </div>
  </div>
</nav>